name: ai
description: Library that help construct neural networks (AI) with Dart. 
  Each type of network is one object and designed as close as possible to human brain.
version: 0.1.8
homepage: https://github.com/YevhenKap/ai
author: Kapelianovych Yevhen <kapelianovych.y.v@gmail.com>
license: MIT

environment:
  sdk: '>=2.1.0-dev.9.4 <3.0.0'

dependencies:
  extended_math: ^0.0.20
  meta: ^1.1.7
  json_annotation: ^2.0.0

dev_dependencies:
  test: ^1.5.3
  json_serializable: ^2.0.1
  build_runner: ^1.0.0
