name: ai
description: Library that help construct neural networks (AI) with Dart.
version: 0.1.10
homepage: https://github.com/YevhenKap/ai
author: Kapelianovych Yevhen <kapelianovych.y.v@gmail.com>
license: MIT

environment:
  sdk: '>=2.1.0-dev.9.4 <3.0.0'

dependencies:
  extended_math: ^0.0.26
  meta: ^1.1.6
  json_annotation: ^2.0.0
  image: ^2.0.7

dev_dependencies:
  test: ^1.5.3
  json_serializable: ^2.0.1
  build_runner: ^1.0.0
